# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        hwi_oauth.user.provider:
            id: hwi_oauth.user.provider
    firewalls:
        main:
            anonymous: ~
            oauth:
                resource_owners:
                    github: "/login/check-github"
                login_path: /login/
                use_forward: false
                failure_path: /login/
                default_target_path: /

                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity
                provider: hwi_oauth.user.provider

    access_control:
        - { path: ^/(?!login|connect), roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
